### ISSUE TITLE
Rename to parcel.ts might have affected website?

### ISSUE THREAD

**Issue by wiowou** [LeaVerou/parsel#65]
Thanks for the great tool!

Did the renaming from parcel.js to parcel.ts break the[ website ](https://projects.verou.me/parsel/)?

**Comment by LeaVerou** [comment]
@jrandolf Whoops, yes, we should link to a file from `/dist/`. @jrandolf can you fix it?

**Comment by jrandolf** [comment]
Sorry about that! Fixed in 7dcc5c2906c8fe5a44a85a5b322325bcf06930bc

**Comment by LeaVerou** [comment]
@jrandolf Thanks for the quick response! Though I'm not sure why we need another build artifact, we can just link to the existing one in `dist/`. Also, if we *are* going to have another build artifact we should gitignore it, right now this built `parsel.js` is in the repo. Remember we are not using GitHub Pages anymore, but Netlify, so not everything that's on the website needs to be part of the repo.

**Comment by jrandolf** [comment]
Hmm, I'm not experienced with Netlify. How does Netlify work in this case? Does it build the entire repo and upload it to Netlify? Also, the PR already imported `parsel.js` from the dist folder, but the import was not `/dist/`, it was relative (`./dist/`). Does this make a difference here?

**Comment by LeaVerou** [comment]
Every serverless platform (e.g. Netlify, Vercel, etc) works the same way: it builds the repo and hosts it.

Not sure why the import was broken, but the `dist/` folder should have been on the website. Perhaps we changed the filename of the generated file? (in which case, we should change it back)

**Comment by jrandolf** [comment]
Hmm, can you verify that the build command is set correctly for Netlify?

**Comment by jrandolf** [comment]
I see the problem now. The above link is to the old URL. @wiowou that site is no longer the correct site, it's https://parsel.verou.me/.

@LeaVerou I see that our page build and deployment still launches to the old https://projects.verou.me/parsel/. I don't believe that CI uses the proper build command for that page. Could you update it?

**Comment by LeaVerou** [comment]
@jrandolf This might be why: https://github.com/LeaVerou/parsel/blob/a7ecd9f4b1c438b225522dffa07b88f091ccd210/package.json#L37

**Comment by jrandolf** [comment]
I'm talking specifically about https://github.com/LeaVerou/parsel/actions/runs/4429680231 You can see the build artifacts don't include the dist folder because the action doesn't built it.

That said, since you are using Netlify, I think it makes sense to disable this action now so the page is disabled and people will look at this repo again for the real site.

**Comment by LeaVerou** [comment]
Yeah, we're not using GitHub Actions or GitHub Pages anymore. I thought I'd leave the GH Pages config up, so that the old URL shows something meaningful, but now that we completely depend on a build process, that doesn't make much sense. Maybe we should add a check that redirects to the new URL if it's not on localhost and not on the new domain?

**Comment by jrandolf** [comment]
Yea, let's do that.
