### ISSUE TITLE
Failed to resolve entry for package "parsel-js". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by alfredriesen** [LeaVerou/parsel#80]
There is dist folder missing!

**Comment by DmitrySharabin** [comment]
I researched a bit, and I think I know why this happened.

In `package.json`, we have the `prepublish` script, which (as its name implies) should run before the package is published on `npm`: https://github.com/LeaVerou/parsel/blob/91b576a2b735f85c61a3ad009eeccfd3634200d5/package.json#L22

However, this is no longer true: [`prepublish` is deprecated and does not run during `npm publish`](https://arc.net/l/quote/wzbrqelb). That's why the `dist` folder is missing.

I would suggest replacing the broken `prepublish` script with the `prepare` one ([that runs both during `npm publish` and `npm install`](https://arc.net/l/quote/godatxdt)) so as not to stumble on this issue in the future. I tested it, and it seems to work:

<img width="669" alt="image" src="https://github.com/user-attachments/assets/d33b62c1-be21-4fa4-a1ed-0bb27af3d6e4">


And we should probably publish a patch with the missing `dist` folder, too.

@LeaVerou, what do you think?

**Comment by LeaVerou** [comment]
Agreed

**Comment by DmitrySharabin** [comment]
FIxed in [`v1.2.1`](https://www.npmjs.com/package/parsel-js?activeTab=code)!

<img width="823" alt="image" src="https://github.com/user-attachments/assets/c061e53e-4e87-42bd-88f3-ce285ccaafe4">
